"""Add InternalMessage model

Revision ID: 5af5502f54c3
Revises: 1d5df54c894c
Create Date: 2026-03-03 16:12:49.490777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af5502f54c3'
down_revision = '1d5df54c894c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internal_messages',
    sa.Column('sender_id', sa.String(length=100), nullable=False),
    sa.Column('recipient_id', sa.String(length=100), nullable=False),
    sa.Column('recipient_email', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('internal_messages')
    # ### end Alembic commands ###
