"""Add credit system tables

Revision ID: 9abf847e40d0
Revises: 942812f0c0f7
Create Date: 2026-04-05 11:50:36.216569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abf847e40d0'
down_revision = '942812f0c0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_credits',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('lifetime_spent', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    
    op.create_table('credit_transactions',
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)

    op.create_table('credit_actions',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_actions')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    # Use try-except for credit_transactions as well to be safe
    try:
        op.drop_table('credit_transactions')
    except:
        pass
    op.drop_table('user_credits')
    # ### end Alembic commands ###
